### PR TITLE
Tech radar blip

### PR DESCRIPTION
**Pull request by Carlos-Muniz**
Tech Radar's job is to track the technology the Open edX platform is
using. It is fitting that Tech Radar is also a blip on the Open edX Tech
Radar as it comes to fruition.

The name, ring, quadrant, and a brief description has been added. In
addition, a link to more information has been added as an anchor
element.

### CODE REVIEW

**Review by davidjoy — CHANGES_REQUESTED** [review]
Watch out - it looks like this PR includes all the changes from #8, which you probably don't want.  I'd either remove those commits or just re-create your branch from main and ensure you don't have any of your changes from your other branch.

**Comment by davidjoy** [comment]
(It also makes it very difficult, as a reviewer, to tell what changed here!)

**Comment by sarina** [comment]
@davidjoy I suggested that he branch off the other one. We can review this once the other merges. Maybe that was a bad idea sorry idk

**Comment by davidjoy** [comment]
So long as we don't rebase or squash it's probably fine from a commit perspective. It's just a smidge confusing since the PR is against main.

**Pull request closed without merging**
